### ISSUE TITLE
xboxdevwiki file upload doesn't work

### ISSUE THREAD

**Issue by 0DaveX** [XboxDev/XboxDev#10]
File/Image upload doesn't work for me today (2018-09-02). I had no issues before.
The error message is as shown in the picture.
![xboxdevwiki-uploaderror](https://user-images.githubusercontent.com/28710861/44960871-6e012200-af07-11e8-97e5-f2e15fdc2c02.jpg)

**Comment by JayFoxRox** [comment]
I'm also affected by this, and it prevents me from finishing http://xboxdevwiki.net/Shrek.

**Comment by 0DaveX** [comment]
fixed thanks :)
