### ISSUE TITLE
Thumbnails on xboxdevwiki are broken

### ISSUE THREAD

**Issue by JayFoxRox** [XboxDev/XboxDev#18]
https://xboxdevwiki.net/Xbox_Debug_Monitor#delete_.28Delete_file_or_directory.29 displays the following message instead of an image:

> Error creating thumbnail: Unable to save thumbnail to destination

I assume the disk is full again?

CC @mborgerson @Ernegien

**Comment by JayFoxRox** [comment]
This is still broken and affecting my workflow as I can't view some images that I depend on.
Please fix.

**Comment by espes** [comment]
Let me know if this still happens.
