### ISSUE TITLE
Extract-XISO

### ISSUE THREAD

**Issue by rajaoui123** [XboxDev/XboxDev#22]

**Comment by CakeLancelot** [comment]
`extract-xiso` can be found [here](https://github.com/XboxDev/extract-xiso/). 

If you are having a problem using the program, I recommend asking for support in the xemu or XboxDev Discord. If it's a bug or feature request, that can be reported through the issues tab. In either case, I suggest providing more details so we can understand what you need help with.

**Comment by JayFoxRox** [comment]
This issue doesn't seem to have any purpose. @CakeLancelot added all you could possibly ask for (aside from things which wouldn't fit here).

Closed.
