### ISSUE TITLE
Register #xboxdev and #xboxdev-offtopic on freenode IRC

### ISSUE THREAD

**Issue by JayFoxRox** [XboxDev/XboxDev#3]
We still have to do https://freenode.net/groupreg .
That is because channels starting with a single `#` are reserved on freenode. Whereas channels with `##` are public. We want official status though, so we need to groupreg.

I had originally planned to do this already, but I'm very busy maintaining a handful of projects (in Xbox ecosystem and otherwise). I also have regressions in XQEMU to fix.

**So I'd be grateful if someone else of @XboxDev could do this.**

When this is complete, we need a new issue about bridging XboxDev IRC and XboxDev Discord (unless done immediately).

**Comment by GXTX** [comment]
I'm currently finding it difficult to communicate with key XboxDev maintainers while not using (non-free) Discord, my issues and comments aren't urgent enough to warrant an email or opening an issue with their projects so a simple IRC ping would be nice. This is just a friendly reminder this issue is still open.

**Comment by JayFoxRox** [comment]
> I'm currently finding it difficult to communicate with key XboxDev maintainers while not using (non-free) Discord, my issues and comments aren't urgent enough to warrant an email or opening an issue with their projects so a simple IRC ping would be nice.

You should never have to reach out to maintainers, unless there's a security issue you want to talk about in private (or something similar). Maintainers will often act on GitHub without reading their private messages / chat backlog etc.

GitHub is the official communication platform that we use:

- Known problems should be discussed in issues.
- Code should be submitted through PRs.
- Review comments should be left on PRs.
- Discussions affecting the ecosystem should happen on this repo.

The Discord channels are mostly meant for fast-paced discussions about future developments and for helping users. In some occasions we also use it to keep review discussions short, too (by notifying the author of a broken fix, to avoid another useless review pass). However, generally, all important decisions and review feedback will be left on the PR.

If developers want to get early-input during design of a new feature (and want to avoid Discord), they can also still create an issue (we have done this for a couple of things in the past). This isn't as ideal as discussing things on Discord, but still okay. Often this is not even necessary if they just read past discussions / some past PRs.

---

I'm actually going to close this issue, as I feel like IRC is not suitable for the style of discussion that has evolved on XboxDev Discord. There are often discussions about recent GitHub changes (which are probably too noisy for an IRC bridge), many edits and deletions. Discussions often contain long messages and other features not supported by IRC.
We also host a handful of channels, so mapping this to IRC is very tricky.

Since this issue was opened, a handful of projects have also abandoned IRC, so it will be even harder to attract users in the future.

If someone still wants an IRC bridge they can set it up on their own private bridge probably.
If there will be an official bridge (for a fully FOSS workflow), I assume that it would be a Matrix bridge instead.
