### ISSUE TITLE
Xboxdevwiki thumbnails dont work

### ISSUE THREAD

**Issue by CodeAsm** [XboxDev/XboxDev#8]
> Error creating thumbnail: Unable to save thumbnail to destination

for example here: [http://xboxdevwiki.net/Hardware_Revisions#DVD_Drive](http://xboxdevwiki.net/Hardware_Revisions#DVD_Drive)

**Comment by JayFoxRox** [comment]
Minor update on this, and also XboxDev/xboxdevwiki#7: We had no space left on server.
Temporary workaround is to clear temp files, and rebooting server.

@Grovespaz has admin access now and will investigate as to why this was the case. We'll then consider our options. I assume a new issue will be created (with a more descriptive title) to discuss this.

Closed.
