### ISSUE TITLE
Merge OpenXDK organization into XboxDev

### ISSUE THREAD

**Issue by JayFoxRox** [XboxDev/XboxDev#9]
@OpenXDK only has 2 public repositories:

- cxbe. Which is also hosted on XboxDev ([not as a seperate repo *yet*](https://github.com/XboxDev/nxdk/tree/master/tools/cxbe)).
- xbiso. Whereas XboxDev currently maintains extract-xiso. However, I believe most of us are open to just [replacing extract-xiso with something else](https://github.com/XboxDev/extract-xiso/issues/12).

@OpenXDK only has 1 public member: 

- @thrimbor. Who has also [engaged in nxdk discussions](https://github.com/XboxDev/nxdk/issues/13) and [development](https://github.com/XboxDev/nxdk/pulls?q=is%3Apr+author%3Athrimbor) (when it was still on the @XQEMU organization).

The goals of both organizations seem to align nicely [1]. Getting rid of the OpenXDK organization would help to focus and direct traffic to XboxDev. XboxDev has more momentum right now.

I'd love to hear what the @OpenXDK members (and also @XboxDev members) think about this.

[1] *Except that we wouldn't use the Xbox shield logo by Microsoft; to avoid possible legal issues in the future.*

**Comment by thrimbor** [comment]
Seems like a good idea to me.

I created the OpenXDK organization on GitHub back when I intended to create a "new OpenXDK" by myself, which obviously didn't happen like that.
My suggestion would be that I transfer both repositories to @XboxDev and delete the OpenXDK organization. Even if my versions of cxbe and xbiso don't end up getting used, it would probably be a better place to archive these repositories. Let me know if/when you want this to happen (apparently repository transfers have to get accepted within 24h).

**Comment by JayFoxRox** [comment]
As explained by @thrimbor on Discord:

> The org is gone, xbiso lives in thrimbor/xbiso now (I consider it archived atm).

The cxbe fork has been removed altogether.


Thanks for cooperation! Closed.

**Comment by PatrickvL** [comment]
Cxbx-Reloaded also contains an import of OpenXDK, with many additions to the original code. These additions might be beneficial to either OpenXDK or nxdk too...

**Comment by JayFoxRox** [comment]
That's be appreciated @PatrickvL. However, that's a separate issue for https://github.com/XboxDev/nxdk (or rather: for your fork, to remind people to "upstream").
There's also https://github.com/XboxDev/openxdk, but we should turn into a read-only archive repository because our intention to supersede it by nxdk.

This isssue was strictly about merging the OpenXDK *GitHub organization* (a political / social thing; not so much a technical decision). There wasn't even a copy of OpenXDK *code* hosted on the organization.

**Comment by PatrickvL** [comment]
XboxDev/OpenXDK has no issue-tracker enabled, so I decided to write this suggestion here instead.

I'll create an issue in nxdk too, although I'm not sure how that compares against OpenXDK (any fork)...
